"""Schemas and dataclasses for API requests, responses, and Gemini proposals."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True)
class Proposal:
    """Structured proposal generated by Gemini intent analysis or fallback search."""

    data_code: str
    data_name: str
    pref_code: str
    pref_name: str
    provider_id: str = "mlit"
    provider_name: str = "国土交通省（国土数値情報）"
    year: str = "latest"
    format: str = "GeoJSON"
    summary: str = ""
    confidence: float = 1.0
    location_name: str | None = None
    target_lat: float | None = None
    target_lng: float | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class SearchRequest:
    """Request payload for natural language search."""

    query: str


@dataclass(frozen=True)
class SearchResponse:
    """Response payload for search endpoint."""

    status: str
    proposal: Proposal

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "proposal": self.proposal.to_dict(),
        }


@dataclass(frozen=True)
class DownloadRequest:
    """Request payload for downloading dataset."""

    data_code: str
    pref_code: str = "00"
    year: str = "latest"
    format: str | None = None


@dataclass(frozen=True)
class DownloadResponse:
    """Response payload for download endpoint."""

    status: str
    data_code: str
    pref_code: str
    region_name: str
    year: str
    format: str
    file_name: str
    file_size_mb: float | None
    direct_download_url: str
    drive_file_id: str | None = None
    drive_web_view_link: str | None = None
